### ISSUE TITLE
license not detected by licensecheck

### ISSUE THREAD

**Issue by therjak** [chewxy/math32#16]
The godoc (https://godoc.org/github.com/chewxy/math32) displays a warning
"Requests to this page will redirect to pkg.go.dev/github.com/chewxy/math32 in early 2021. Learn More."
Following this link tells you that the licensecheck (https://pkg.go.dev/github.com/google/licensecheck) did not find a known license and refuses to display the documentation.

**Comment by chewxy** [comment]
That has been fixed. The original licence was supposed to be derived from the Go licence.

**Comment by therjak** [comment]
small typo in the tag: the version number changed to 1.07 instead of 1.0.7
