### ISSUE TITLE
Semantic version typo means go mod won't install v1.0.7 or v1.0.8

### ISSUE THREAD

**Issue by finnbear** [chewxy/math32#18]
![image](https://user-images.githubusercontent.com/20015102/115975636-3f527280-a51b-11eb-9288-61a3484c81fc.png)

As you cans see in this screenshot of releases, `v1.0.7` is incorrectly marked as `v1.07` and `v1.0.8` is incorrectly marked as `v1.08`.

As a result, when I run `go get -u github.com/chewxy/math32@latest`, I end up with `github.com/chewxy/math32 v1.0.6`.

I need the latest version as `Sqrt` doesn't work on ARM prior to it.

Workaround: `go get -u github.com/chewxy/math32@v1.08`

**Comment by chewxy** [comment]
Fixed.
