### ISSUE TITLE
Geometric functions

### ISSUE THREAD

**Issue by soypat** [chewxy/math32#24]
What is the possibility of implementing `Sin`, `Cos` and others as pure 32 bit software? 

I've implemented some (glibc as reference) here https://github.com/soypat/soft-math.

**Comment by chewxy** [comment]
Sure thing. I welcome all PRs

**Comment by soypat** [comment]
@chewxy I've added a PR to include `Acos` and `Asin`!

**Comment by soypat** [comment]
Closed with the latest addition of Tan!
