### ISSUE TITLE
Fix tests.

### ISSUE THREAD

**Issue by chewxy** [chewxy/math32#4]
TODO: 

Thanks to @docmerlin for the headsup

* [ ] find the correct all_test.go from old git repos.
* [ ] travisify this repo

**Comment by chewxy** [comment]
Yes I am aware. Much of these tests are sensitivity related. It takes quite abit of work to actually fix them all. I welcome all PRs

**Comment by soypat** [comment]
I have fixed existing tests, added smoke tests for all supported architectures/OSes (see https://github.com/chewxy/math32/blob/master/math32_test.go) and added github actions for validating PRs. Can we consider this closed?

**Comment by chmike** [comment]
That is very impressive and a highly valuable work. Congratulation and thank you very much.

**Comment by soypat** [comment]
Alright, closing now!
